# Generated by Django 5.0.4 on 2024-04-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='newsletters',
            field=models.ManyToManyField(to='main_app.newsletter'),
        ),
    ]
